railwebsite/config/routes.rb
Rails.application.routes.draw do
  resources :databases
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

railwebsite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

railwebsite/app/models/database.rb
class Database < ApplicationRecord
end

railwebsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

railwebsite/app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  before_action :set_database, only: %i[ show edit update destroy ]

  # GET /databases or /databases.json
  def index
    @databases = Database.all
  end

  # GET /databases/1 or /databases/1.json
  def show
  end

  # GET /databases/new
  def new
    @database = Database.new
  end

  # GET /databases/1/edit
  def edit
  end

  # POST /databases or /databases.json
  def create
    @database = Database.new(database_params)

    respond_to do |format|
      if @database.save
        format.html { redirect_to database_url(@database), notice: "Database was successfully created." }
        format.json { render :show, status: :created, location: @database }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /databases/1 or /databases/1.json
  def update
    respond_to do |format|
      if @database.update(database_params)
        format.html { redirect_to database_url(@database), notice: "Database was successfully updated." }
        format.json { render :show, status: :ok, location: @database }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /databases/1 or /databases/1.json
  def destroy
    @database.destroy!

    respond_to do |format|
      format.html { redirect_to databases_url, notice: "Database was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_database
      @database = Database.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def database_params
      params.require(:database).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

railwebsite/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end  
end

railwebsite/app/helpers/application_helper.rb
module ApplicationHelper
end

railwebsite/app/helpers/databases_helper.rb
module DatabasesHelper
end

railwebsite/app/helpers/home_helper.rb
module HomeHelper
end

railwebsite/app/views/databases/_database.html.erb
<div id="<%= dom_id database %>">
  <p>
    <strong>First name:</strong>
    <%= database.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= database.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= database.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= database.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= database.twitter %>
  </p>

</div>

railwebsite/app/views/databases/_form.html.erb
<%= form_with(model: database) do |form| %>
  <% if database.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(database.errors.count, "error") %> prohibited this database from being saved:</h2>

      <ul>
        <% database.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

railwebsite/app/views/databases/edit.html.erb
<h1>Editing database</h1>

<%= render "form", database: @database %>

<br>

<div>
  <%= link_to "Show this database", @database %> |
  <%= link_to "Back to databases", databases_path %>
</div>

railwebsite/app/views/databases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Databases</h1>

<div id="databases">
  <% @databases.each do |database| %>
    <%= render database %>
    <p>
      <%= link_to "Show this database", database %>
    </p>
  <% end %>
</div>

<%= link_to "New database", new_database_path %>

railwebsite/app/views/databases/new.html.erb
<h1>New database</h1>

<%= render "form", database: @database %>

<br>

<div>
  <%= link_to "Back to databases", databases_path %>
</div>

railwebsite/app/views/databases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @database %>

<div>
  <%= link_to "Edit this database", edit_database_path(@database) %> |
  <%= link_to "Back to databases", databases_path %>

  <%= button_to "Destroy this database", @database, method: :delete %>
</div>

railwebsite/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Rails App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Databases', databases_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Database', new_database_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

railwebsite/app/views/home/about.html.erb
<h1>About us...</h1>

railwebsite/app/views/home/index.html.erb
<h1>Hello world</h1>

railwebsite/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails website</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>